root: true
extends: ['@cherryblossom/eslint-config/node']
reportUnusedDisableDirectives: true
settings:
  jsdoc:
    mode: typescript
ignorePatterns:
  - dist/
  - test/
rules:
  '@typescript-eslint/prefer-readonly-parameter-types': 0
  import/no-unused-modules: 0
  import/prefer-default-export: 0
