default: true
MD003: # Heading style
  style: atx
MD004: # Unordered list style
  style: dash
MD009: # Trailing spaces
  strict: true
MD013: # Line length
  stern: true
MD024: # Multiple headings with the same content
  siblings_only: true
MD035: # Horizontal rule style
  style: ---
MD046: # Code block style
  style: fenced
MD048: # Code fence style
  style: backtick
