name: CI
on:
- push
- pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:

    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node }}

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.3.0
        run_install: true

    - name: Lint
      run: pnpm lint:all
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm test

    - name: Upload build data
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2.2.3
      with:
        name: dist
        path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    env:
      NODE_VERSION: 14
    steps:

    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: crazy-max/ghaction-import-gpg@v3.1.0
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git-user-signingkey: true
        git-commit-gpgsign: true

    - name: Cache pnpm modules
      uses: actions/cache@v2.1.5
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/package.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.NODE_VERSION }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.3.0
        run_install: true

    - name: Download build data
      uses: actions/download-artifact@v2.0.9
      with:
        name: dist
        path: dist

    - name: Release
      run: pnpx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
